version: "3"
services:
  cyberchef:
    container_name: cyberchef
    image: mpepping/cyberchef:v9.37.3
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: homeserver
      traefik.enable: true
      traefik.http.routers.cyberchef.rule: Host(`cyberchef.${SERVER_DOMAIN}`)
      traefik.http.routers.cyberchef.entrypoints: websecure
      traefik.http.services.cyberchef.loadbalancer.server.port: 8000

networks:
  traefik:
    name: homeserver
    external: true