version : '3.7'
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor@sha256:ddadf3e2fd880deb4e0f3606d34a0d9da1165e3801116075d98a1901635dc9e8
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /volume1/@docker:/var/lib/docker:ro
    networks:
      - traefik
    labels:
      my.zone: homeserver
      traefik.enable: true
      traefik.http.routers.cadvisor.rule: Host(`cadvisor.${SERVER_DOMAIN}`)
      traefik.http.routers.cadvisor.entrypoints: websecure
      traefik.http.services.cadvisor.loadbalancer.server.port: 8080

networks:
  traefik:
    name: homeserver
    external: true