version: "3.8"
services:
  cloudflared:
    image: cloudflare/cloudflared:2022.5.1
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token ${TOKEN}
    environment:
      - TOKEN=${TOKEN}
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik

networks:
  traefik:
    name: homeserver
    external: true
