version: "3.6"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - heimdall-volume:/config
    container_name: heimdall
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    labels:
      my.zone: homeserver
      traefik.enable: true
      traefik.http.routers.heimdall.rule: Host(`homeserver.${SERVER_DOMAIN}`)
      traefik.http.routers.heimdall.entrypoints: websecure
      traefik.http.services.heimdall.loadbalancer.server.port: 80

networks:
  traefik:
    name: homeserver
    external: true

volumes:
  heimdall-volume: